### PR TITLE
Allow push to work even if no changes were made

### PR DESCRIPTION
**Pull request by bclinkinbeard**
I'm not sure if this is the correct way to make this work, but I don't understand the `gity` source well enough to do it another way. :)

Open to suggestions for better ways to accomplish this.

### CODE REVIEW

**Comment by stevenmiller888** [comment]
@bclinkinbeard What's the use-case for wanting to push when no changes were made? Just want to understand this a bit better :)

**Comment by bclinkinbeard** [comment]
I'm using `git-auto` to create an Atom package that will help non-devs use Git and GitHub. My package has a "Save" option, and a "Save and Share" option, the latter being commit+push. So I'm really just trying to make it more flexible to let them push any time they want to.

That being said, I understand it might be kind of a niche feature request. I can just use `gity` directly if you don't want to add this. I just discovered, to my surprise, `git commit -am "Changed stuff" && git push` fails to push if there are no changes so maybe the existing behavior is "correct".

`¯\_(ツ)_/¯`

**Comment by stevenmiller888** [comment]
Oh nice that's awesome! Would love to check that out when you release it. I'm happy to add this in. What do you think about adding this feature via a force push option? The command could be something like `git auto -pf`, and then we could do `git.push('-f origin master');`

**Comment by bclinkinbeard** [comment]
Sounds great!

**Comment by stevenmiller888** [comment]
Sweet! Do you want to implement that or should I?

**Comment by bclinkinbeard** [comment]
Oh, good question. :) Would it just be adding a `force` option to the code here? I'm not clear on how the `git.push('-f origin master');` would work (in `gity`, right?).

**Comment by stevenmiller888** [comment]
Yeah it would just be adding the option in bin/git-auto and adding a conditional in lib/index.js to run push with force if the force option is present, if not, run the regular push. Haha yeah it's a gity thing :)

**Comment by bclinkinbeard** [comment]
OK I'm still confused. :) I added `if (opts.push && opts.force) git.push('-f origin master');` locally, which doesn't help. Did you mean we should add the force option in addition to the change detection already in this PR, or instead of it?

**Comment by stevenmiller888** [comment]
I was thinking only the force option. I just pushed to master. Can you take a look in there and let me know if that's what you were thinking?

**Comment by bclinkinbeard** [comment]
That doesn't seem to actually change the behavior. Calling `commit` when there are no changes prevents the subsequent `push` from working, even if `-f` is specified. I verified that is the case with Git itself.

**Comment by stevenmiller888** [comment]
Ohhh, gotcha. Yeah just tested that out and saw the same thing. Curious, will this matter to the user of your atom package? They won't know the difference if there are no changes anyway, right?

**Comment by bclinkinbeard** [comment]
It won't matter to the user because if we don't change `git-auto` to support this I will just use `gity` directly. :)

Basically, if I can't depend on `git-auto` to always push when `opts.push` is true, I have to use `gity` to check the status, detect the lack of changes, and then use `gity` to push. At that point the only benefit of using `git-auto` at all is the automated commit messages. (Which, I guess I could pretty easily pull that code into my project and remove `git-auto` entirely.)

I dunno, I don't feel strongly either way, but I think the code currently in this PR makes `git-auto` a bit more of a general purpose simplifier for working with Git.

**Comment by stevenmiller888** [comment]
I see. Thanks for explaining! I'll merge it and publish a new version :)

**Comment by bclinkinbeard** [comment]
Thanks!

**Comment by bclinkinbeard** [comment]
FYI, I just published the package. :) https://atom.io/packages/atom-gist-dev

It's super early and rough, but was fun to build.

**Comment by stevenmiller888** [comment]
Nice dude! Just downloaded it. Looks really cool :)

**Pull request merged**
